"""empty message

Revision ID: 315bf5de80da
Revises: 1ea2e867ea80
Create Date: 2016-11-23 11:20:17.195703

"""

# revision identifiers, used by Alembic.
revision = '315bf5de80da'
down_revision = '1ea2e867ea80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('style_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloth', sa.String(length=10), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.Column('totoal', sa.Integer(), nullable=True),
    sa.Column('coming', sa.Integer(), nullable=True),
    sa.Column('sale', sa.Integer(), nullable=True),
    sa.Column('receved', sa.Integer(), nullable=True),
    sa.Column('storge', sa.Integer(), nullable=True),
    sa.Column('left', sa.Integer(), nullable=True),
    sa.Column('diff', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog')
    op.drop_table('colors')
    op.drop_table('styles')
    ### end Alembic commands ###
