"""empty message

Revision ID: e52cb04ee04e
Revises: 1ea2e867ea80
Create Date: 2016-11-22 16:49:57.326746

"""

# revision identifiers, used by Alembic.
revision = 'e52cb04ee04e'
down_revision = '1ea2e867ea80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
